[build-system]
requires = [
    "setuptools>=75.6.0",
    "wheel"
]

build-backend = "setuptools.build_meta"

[project]
name = "jatszoter-agent"
version = "0.0.1"
description = "Agent for run playgrounds"
readme = "README.md"

[project.license]
text = "MIT"

authors = [
    {name = "zombig", email = "me@zombig.name"}
]

dependencies = [
    'annotated-types==0.7.0',
    'anyio==4.7.0',
    'certifi==2024.8.30',
    'charset-normalizer==3.4.0',
    'click==8.1.7',
    'docker==7.1.0',
    'fastapi==0.115.6',
    'h11==0.14.0',
    'idna==3.10',
    'pydantic==2.10.3',
    'pydantic_core==2.27.1',
    'requests==2.32.3',
    'sniffio==1.3.1',
    'starlette==0.41.3',
    'typing_extensions==4.12.2',
    'urllib3==2.2.3',
    'uvicorn==0.32.1',
]

requires-python = ">=3.12"

[project.scripts]
jatszoter-agent = "agent.__main__:main"

[tool.setuptools.packages.find]
where = ["../../src"]
include = ["agent*"]
