[tool.poetry]
name = "jatszoter-agent"
version = "0.1.0"
description = "Jatszoter Agent"
authors = ["zombig <me@zombig.name>"]
license = "MIT License"
readme = "README.md"

packages = [{ include = "jatszoter/agent", from = "src" }]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.scripts]
jatszoter-agent = "jatszoter.agent.__main__:main"
